c8

diff --git a/.github/workflows/ci-cd-feature-branch.yml b/.github/workflows/ci-cd-feature-branch.yml
--- a/.github/workflows/ci-cd-feature-branch.yml
+++ b/.github/workflows/ci-cd-feature-branch.yml
@@ -68,6 +68,15 @@ jobs:
       #       git checkout staging
       #       git merge ${{ github.ref }} --no-ff --allow-unrelated-histories -m "Merge feature branch ${{ github.head_ref }} into staging"
       #       git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} staging
+
+      #   - name: Merge feature branch into staging
+      #     run: |
+      #       git fetch origin staging
+      #       git checkout staging
+      #       git config --global user.email "ketanchaudharypoonia@gmail.com"
+      #       git config --global user.name "Ketan-Chaudhary"
+      #       git merge ${{ github.ref }} --no-ff --allow-unrelated-histories -m "Merge feature branch ${{ github.head_ref }} into staging"
+      #       git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} staging
       - name: Merge feature branch into staging
         run: |
           git fetch origin staging
@@ -75,4 +84,8 @@ jobs:
           git config --global user.email "ketanchaudharypoonia@gmail.com"
           git config --global user.name "Ketan-Chaudhary"
           git merge ${{ github.ref }} --no-ff --allow-unrelated-histories -m "Merge feature branch ${{ github.head_ref }} into staging"
+          if [ $? -ne 0 ]; then
+              echo "Merge conflict detected, aborting merge."
+              exit 1
+          fi
           git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} staging
